In [1]:
import numpy as np

In [2]:
# Array 1D
d1 = np.array([1, 2, 3])

print(d1)

[1 2 3]


In [3]:
# -----------------------------------------------------
# Qual é o formato do arry?
d1.shape

(3,)

In [4]:
# Quantas dimenções é o arry?
d1.ndim


1

In [5]:
# O tipo do arry?
d1.dtype

dtype('int64')

In [6]:
# -----------------------------------------------------
# Array 2D
d2 = np.array([[1, 2, 3], [4, 5, 6]])

print(d2)

[[1 2 3]
 [4 5 6]]


In [7]:
# -----------------------------------------------------
# Qual é o formato do arry?
d2.shape

(2, 3)

In [8]:
# Quantas dimenções é o arry?
d2.ndim

2

In [9]:
# O tipo do arry?
d2.dtype

dtype('int64')

In [10]:
# -----------------------------------------------------
# Array 3D
d3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(d3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [11]:
# -----------------------------------------------------
# Qual é o formato do arry?
d3.shape

(2, 2, 3)

In [12]:
# Quantas dimenções é o arry?
d3.ndim

3

In [13]:

# O tipo do arry?
d3.dtype

dtype('int64')